name: BlueCat Raffle Cron

on:
  schedule:
    # Every 15 minutes (safe + handles DST). Change to "5 * * * *" for hourly.
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

# Avoid two runs overlapping if one takes longer than expected
concurrency:
  group: raffle-ops
  cancel-in-progress: false

# Least-privilege permissions for this workflow
permissions:
  contents: read

jobs:
  run-ops:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        # If there's ever a lock mismatch, fall back to npm i
        run: npm ci || npm i

      - name: Close/Finalize/Open rounds
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          RAFFLE_ADDRESS: ${{ secrets.RAFFLE_ADDRESS }}
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
          MASTER_SECRET: ${{ secrets.MASTER_SECRET }}
        run: npm run ops:run
